In [1]:
import numpy as np

# First Section

In [2]:
first = np.array([[1,2,3], [4, 5, 6]])

In [3]:
first


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
second = np.array([[7,8,9], [10, 11, 12]])

In [5]:
first + second


array([[ 8, 10, 12],
       [14, 16, 18]])

In [6]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
second / 2

array([[3.5, 4. , 4.5],
       [5. , 5.5, 6. ]])

In [9]:
print(first[0, 2])

3


In [10]:
print(first[1,2])

6


In [12]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.concatenate((first, second), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [15]:
np.concatenate((np.array([1,2,3,4 ]), np.array([8, 2, 3, 4])))

array([1, 2, 3, 4, 8, 2, 3, 4])

In [18]:
ar_zeros = np.zeros((3, 2), dtype=float)

In [19]:
ar_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
one_arr = np.ones((3, 4))

In [21]:
one_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.random.random(33)

array([0.45352178, 0.08327852, 0.9903832 , 0.85208588, 0.28345157,
       0.49357824, 0.65527306, 0.11002075, 0.90935542, 0.78002968,
       0.64457556, 0.26545004, 0.06230473, 0.39101052, 0.52281936,
       0.79261622, 0.86304985, 0.16959818, 0.68861607, 0.70613262,
       0.61675194, 0.58240257, 0.66461868, 0.21198049, 0.37140341,
       0.03332993, 0.43758614, 0.71017997, 0.13672794, 0.86502681,
       0.65082202, 0.66498462, 0.58836913])

In [28]:
np.random.randint(10, 20, size=(2, 4))

array([[12, 12, 18, 18],
       [18, 18, 18, 11]], dtype=int32)

In [33]:
np.random.uniform(10, 50, size=(3, 8))

array([[18.74741582, 35.43608879, 28.79225619, 27.22319501, 12.59895254,
        32.62494087, 29.83930242, 39.06211257],
       [27.96705403, 42.48878585, 34.43921936, 23.70043215, 21.2778306 ,
        23.47502263, 48.52605475, 19.69074486],
       [10.37409869, 24.94629217, 37.93917177, 13.87283288, 36.61247764,
        27.49776149, 28.16554187, 13.83350375]])

In [35]:
np.random.choice(np.array([1,2,3]), size=20)

array([1, 3, 1, 2, 1, 2, 1, 1, 1, 3, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1])

## Calculator Total and average orders


In [36]:
order_qty = np.array([[1, 2, 3, 4], [7, 8, 9, 10]])

In [37]:
order_qty

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [40]:
total_qty = np.sum(order_qty, axis=0)

In [41]:
total_qty

array([ 8, 10, 12, 14])

In [42]:
average_qty = np.mean(order_qty, axis=0)

In [43]:
average_qty

array([4., 5., 6., 7.])

In [44]:
average_qty = np.mean(order_qty, axis=1)

In [45]:
average_qty

array([2.5, 8.5])

# Next section


In [47]:
product_rating = np.array([[4.5, 3.2, 4.7], [4.3, 3.8, 2.8], [3.5, 4.2, 2.0]])

In [48]:
average_category = np.mean(product_rating, axis=1)

In [49]:
average_category

array([4.13333333, 3.63333333, 3.23333333])

In [50]:
aver_cat_per = np.mean(product_rating, axis=0)

In [51]:
aver_cat_per

array([4.1       , 3.73333333, 3.16666667])

In [52]:
max_rating = np.max(product_rating, axis=0)

In [53]:
max_rating

array([4.5, 4.2, 4.7])

# Generation of the sample stock data

In [54]:
companies = ['Google', 'Apple', 'Yandex']

In [55]:
days = ['Monday 1 April', 'Thuesday 2 December']

In [56]:
price_types = ['Open', 'Close', 'High', 'Low']

In [61]:
np.random.seed(1)
stock_prices = np.round(np.random.random((len(companies), len(days), len(price_types))), 3)

In [62]:
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [63]:
stock_prices.shape

(3, 2, 4)

In [65]:
for i, company in enumerate(companies):
    print(f"Stock prices for {company} : ")
    for j, day in enumerate(days):
        print(f"Day : {day}")
        for k, price in enumerate(price_types):
            print(f"{price} : {stock_prices[i,j,k]}")
        print()
    print()

Stock prices for Google : 
Day : Monday 1 April
Open : 0.417
Close : 0.72
High : 0.0
Low : 0.302

Day : Thuesday 2 December
Open : 0.147
Close : 0.092
High : 0.186
Low : 0.346


Stock prices for Apple : 
Day : Monday 1 April
Open : 0.397
Close : 0.539
High : 0.419
Low : 0.685

Day : Thuesday 2 December
Open : 0.204
Close : 0.878
High : 0.027
Low : 0.67


Stock prices for Yandex : 
Day : Monday 1 April
Open : 0.417
Close : 0.559
High : 0.14
Low : 0.198

Day : Thuesday 2 December
Open : 0.801
Close : 0.968
High : 0.313
Low : 0.692


